#!/bin/bash

set -euo pipefail

sql_escape()
{
    local s="${1-}"
    s="${s//\'/\'\'}"
    if [[ "$s" == *'`'* ]]; then
        echo "ERROR: value contains a backtick, refusing to seed" >&2
        exit 1
    fi
    printf '%s' "$s"
}

require_var()
{
    local name="$1"
    local val="${!name-}"
    if [[ -z "$val" ]]; then
        echo "ERROR: required environment variable $name is not set" >&2
        exit 1
    fi
}

require_var ADMIN_1
require_var PASSWORD_HASH_1
require_var KIDUSER
require_var KIDPASS_HASH

if [[ -n "${ADMIN_2-}" || -n "${PASSWORD_HASH_2-}" ]]; then
    require_var ADMIN_2
    require_var PASSWORD_HASH_2
fi

USER_VALUES="  ('$(sql_escape "$ADMIN_1")',      '$(sql_escape "$PASSWORD_HASH_1")', 'admin'),"
if [[ -n "${ADMIN_2-}" ]]; then
    USER_VALUES+=$'\n'
    USER_VALUES+="  ('$(sql_escape "$ADMIN_2")',      '$(sql_escape "$PASSWORD_HASH_2")', 'admin'),"
fi
USER_VALUES+=$'\n'
USER_VALUES+="  ('$(sql_escape "$KIDUSER")',      '$(sql_escape "$KIDPASS_HASH")',    'kid');"

SQL_FILE="$(mktemp)"
trap 'rm -f "$SQL_FILE"' EXIT

cat > "$SQL_FILE" <<SQL
-- Auto-generated by 002-seed.sh on first DB init.
-- Inserts the seeded users.

USE \`$MYSQL_DATABASE\`;

INSERT IGNORE INTO \`users\` (\`username\`, \`password_hash\`, \`role\`) VALUES
$USER_VALUES
SQL

DB_USER="${MYSQL_USER:-root}"
DB_PASS="${MYSQL_PASSWORD:-${MYSQL_ROOT_PASSWORD:-}}"

if [[ -n "$DB_PASS" ]]; then
    mysql --default-character-set=utf8mb4 -u"$DB_USER" -p"$DB_PASS" < "$SQL_FILE"
else
    mysql --default-character-set=utf8mb4 -u"$DB_USER"            < "$SQL_FILE"
fi

echo "002-seed.sh: seeded ADMIN_1 and KIDUSER; ADMIN_2 is optional."
